### ISSUE TITLE
Lotus problem loading data files

### ISSUE THREAD

**Issue by binlbl** [AChavignon/PALA#10]
When I load data files, e.g. in vivo mouse tumor data, Lotus always gives errors:
"Your matrices should have variable name IQ"
![image](https://user-images.githubusercontent.com/66796464/171953556-141ea66e-38e5-401c-9505-f0bb5b9f36d9.png)

But I checked in MATLAB, the .mat file did have variable name IQ.

**Comment by bheiles** [comment]
Hi @binlbl,

Which version of Lotus are you using? Can you send a file snippet?

**Comment by bheiles** [comment]
Hi @binlbl 

Could you tell me which version of Lotus you're using, or make sure you're up to date? Can you post a file snippet please

> When I load data files, e.g. in vivo mouse tumor data, Lotus always gives errors: "Your matrices should have variable name IQ" ![image](https://user-images.githubusercontent.com/66796464/171953556-141ea66e-38e5-401c-9505-f0bb5b9f36d9.png)
> 
> But I checked in MATLAB, the .mat file did have variable name IQ.

**Comment by binlbl** [comment]
> Could you tell me which version of Lotus you're using, or make sure you're up to date? Can you post a file snippet please
Thanks, it is version 1.2, I don't know how to get a file snippet. 
I selected several .mat files from folder PALA_data_InVivoMouseTumor\IQ and then press the"Add" and  "Done" button, the above dialog warning appears.

**Comment by binlbl** [comment]
Just found that if I open two "Load Data" dialog ( click "1.Load Data" button the second time), and load data in the second dialog, I can load data successfully.
