### ISSUE TITLE
PALA_data_folder missing

### ISSUE THREAD

**Issue by GitOfHaiyang** [AChavignon/PALA#4]
There seems to be no data to support the running code... Can I get the data from somewhere？

**Comment by AChavignon** [comment]
Hi, data can be download at https://doi.org/10.5281/zenodo.4343435
The related article is currently in press and may be available before the end of the year.

**Comment by GitOfHaiyang** [comment]
Thanks~

**Comment by GitOfHaiyang** [comment]
Thanks and Congratulations










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AChavignon/PALA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月24日(星期五) 下午5:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AChavignon/PALA] PALA_data_folder missing (#4)





 
Hi, data can be download at https://doi.org/10.5281/zenodo.4343435
 The related article is currently in press and may be available before the end of the year.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
